import os
from dotenv import load_dotenv

load_dotenv()

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
MAX_COMMENTS = 20000
SPAM_THRESHOLD = 3
CACHE_TIMEOUT = 3600
SECRET_KEY = os.getenv("SECRET_KEY")

NEUTRAL_TARGET_MIN_PCT = 10
NEUTRAL_TARGET_MAX_PCT = 20
